## origin possibilities and their associated stats
Origins = {
           'Athletic':{'health':'2', 'movement':'40', 'desc':' Physical prowess has always come naturally to you, and all your life you’ve been in good shape. It still takes a modest amount of upkeep and discipline to maintain, but that has never been a hard decision for you to prioritize such things. You likely play physical sports, work out in your spare time, and maintain a healthy lifestyle.'},
           'Brainy':{'health':'1', 'movement':'25', 'desc':'You love studying, learning, and reading about, well – everything. You live to learn, and you have learned a lot in your time. With all your time spent with your nose in books and such, you haven’t had time to prioritize things like how to fight, or much else beyond some personal hobbies.'},
           'Comedic':{'health':'1', 'movement':'30', 'desc':'Class clown. Jester. Wiseacre. Smart-aleck. There are a number of different terms and names often applied to a person like you – someone who uses comedy and levity to get through life’s little issues. While you have leaned on your charm and lighthearted cunning to get out of some situations, it has also thrown you in the thick of things on more than a few occasions.'},
           'Curious':{'health':'1', 'movement':'35', 'desc':' Ever since you were very young, you never have been able to keep your nose out of mysteries and the unknown. You live for discovering new things – especially if you’ve been told you aren’t supposed to know about it. Some might have called you nosey, or perhaps an eavesdropper, but it wasn’t really your fault – you’re just naturally interested in the unknown.'}
           }

## Ranger Levels are hard coded in a list
## the program searches for the appropriate boosts 
## then applies it to the base scores
Levels = {
    "Pink": {
        1:{'strength': 0, 'speed': 2, 'smarts': 0, 'social': 1, 'power': 2},
        2:{'strength': 0, 'speed': 2, 'smarts': 0, 'social': 2, 'power': 2},
        3:{'strength': 0, 'speed': 2, 'smarts': 1, 'social': 2, 'power': 2},
        4:{'strength': 1, 'speed': 2, 'smarts': 2, 'social': 2, 'power': 4},
        5:{'strength': 1, 'speed': 3, 'smarts': 2, 'social': 2, 'power': 4},
        6:{'strength': 1, 'speed': 3, 'smarts': 2, 'social': 3, 'power': 4},
        7:{'strength': 1, 'speed': 3, 'smarts': 3, 'social': 3, 'power': 6},
        8:{'strength': 2, 'speed': 3, 'smarts': 3, 'social': 3, 'power': 6},
        9:{'strength': 2, 'speed': 4, 'smarts': 3, 'social': 3, 'power': 6},
        10:{'strength': 2, 'speed': 4, 'smarts': 3, 'social': 4, 'power': 8},
        11:{'strength': 2, 'speed': 4, 'smarts': 4, 'social': 4, 'power': 8},
        12:{'strength': 3, 'speed': 4, 'smarts': 4, 'social': 4, 'power': 8},
        13:{'strength': 3, 'speed': 5, 'smarts': 4, 'social': 4, 'power': 10},
        14:{'strength': 3, 'speed': 5, 'smarts': 4, 'social': 5, 'power': 10},
        15:{'strength': 3, 'speed': 5, 'smarts': 5, 'social': 5, 'power': 10},
        16:{'strength': 3, 'speed': 6, 'smarts': 5, 'social': 5, 'power': 12},
        17:{'strength': 3, 'speed': 6, 'smarts': 5, 'social': 6, 'power': 12},
        18:{'strength': 3, 'speed': 7, 'smarts': 5, 'social': 6, 'power': 12},
        19:{'strength': 3, 'speed': 7, 'smarts': 5, 'social': 7, 'power': 14},
        20:{'strength': 3, 'speed': 8, 'smarts': 5, 'social': 7, 'power': 14}
            },
     "Red": {
        1:{'strength': 2, 'speed': 0, 'smarts': 0, 'social': 1, 'power': 2},
        2:{'strength': 2, 'speed': 0, 'smarts': 0, 'social': 2, 'power': 2},
        3:{'strength': 2, 'speed': 1, 'smarts': 0, 'social': 2, 'power': 2},
        4:{'strength': 2, 'speed': 1, 'smarts': 1, 'social': 2, 'power': 2},
        5:{'strength': 3, 'speed': 1, 'smarts': 1, 'social': 2, 'power': 4},
        6:{'strength': 3, 'speed': 1, 'smarts': 1, 'social': 3, 'power': 4},
        7:{'strength': 3, 'speed': 2, 'smarts': 1, 'social': 3, 'power': 4},
        8:{'strength': 3, 'speed': 2, 'smarts': 2, 'social': 3, 'power': 4},
        9:{'strength': 4, 'speed': 2, 'smarts': 2, 'social': 3, 'power': 6},
        10:{'strength': 4, 'speed': 2, 'smarts': 2, 'social': 4, 'power': 6},
        11:{'strength': 4, 'speed': 3, 'smarts': 2, 'social': 4, 'power': 6},
        12:{'strength': 4, 'speed': 3, 'smarts': 3, 'social': 4, 'power': 6},
        13:{'strength': 5, 'speed': 3, 'smarts': 3, 'social': 4, 'power': 8},
        14:{'strength': 5, 'speed': 3, 'smarts': 3, 'social': 5, 'power': 8},
        15:{'strength': 5, 'speed': 4, 'smarts': 3, 'social': 5, 'power': 8},
        16:{'strength': 6, 'speed': 4, 'smarts': 3, 'social': 5, 'power': 8},
        17:{'strength': 6, 'speed': 4, 'smarts': 3, 'social': 6, 'power': 10},
        18:{'strength': 7, 'speed': 4, 'smarts': 3, 'social': 6, 'power': 10},
        19:{'strength': 6, 'speed': 4, 'smarts': 3, 'social': 7, 'power': 10},
        20:{'strength': 7, 'speed': 4, 'smarts': 3, 'social': 7, 'power': 10}
            },
    "Blue": {
        1:{'strength': 0, 'speed': 1, 'smarts': 2, 'social': 0, 'power': 2},
        2:{'strength': 0, 'speed': 2, 'smarts': 2, 'social': 0, 'power': 2},
        3:{'strength': 0, 'speed': 2, 'smarts': 2, 'social': 1, 'power': 2},
        4:{'strength': 1, 'speed': 2, 'smarts': 2, 'social': 1, 'power': 4},
        5:{'strength': 1, 'speed': 2, 'smarts': 3, 'social': 1, 'power': 4},
        6:{'strength': 1, 'speed': 3, 'smarts': 3, 'social': 1, 'power': 4},
        7:{'strength': 1, 'speed': 3, 'smarts': 3, 'social': 2, 'power': 6},
        8:{'strength': 2, 'speed': 3, 'smarts': 3, 'social': 2, 'power': 6},
        9:{'strength': 2, 'speed': 3, 'smarts': 4, 'social': 2, 'power': 6},
        10:{'strength': 2, 'speed': 4, 'smarts': 4, 'social': 2, 'power': 8},
        11:{'strength': 2, 'speed': 4, 'smarts': 4, 'social': 3, 'power': 8},
        12:{'strength': 3, 'speed': 4, 'smarts': 4, 'social': 3, 'power': 8},
        13:{'strength': 3, 'speed': 4, 'smarts': 5, 'social': 3, 'power': 10},
        14:{'strength': 3, 'speed': 5, 'smarts': 5, 'social': 3, 'power': 10},
        15:{'strength': 3, 'speed': 5, 'smarts': 5, 'social': 4, 'power': 10},
        16:{'strength': 3, 'speed': 5, 'smarts': 6, 'social': 4, 'power': 12},
        17:{'strength': 3, 'speed': 6, 'smarts': 6, 'social': 4, 'power': 12},
        18:{'strength': 3, 'speed': 6, 'smarts': 7, 'social': 4, 'power': 12},
        19:{'strength': 3, 'speed': 7, 'smarts': 7, 'social': 4, 'power': 14},
        20:{'strength': 3, 'speed': 7, 'smarts': 8, 'social': 4, 'power': 14}
        },
    'Green': {
        1:{'strength': 2, 'speed': 1, 'smarts': 0, 'social': 0, 'power': 2},
        2:{'strength': 2, 'speed': 2, 'smarts': 0, 'social': 0, 'power': 2},
        3:{'strength': 2, 'speed': 2, 'smarts': 0, 'social': 1, 'power': 3},
        4:{'strength': 2, 'speed': 2, 'smarts': 1, 'social': 1, 'power': 3},
        5:{'strength': 3, 'speed': 2, 'smarts': 1, 'social': 1, 'power': 4},
        6:{'strength': 3, 'speed': 3, 'smarts': 1, 'social': 1, 'power': 4},
        7:{'strength': 3, 'speed': 3, 'smarts': 1, 'social': 2, 'power': 5},
        8:{'strength': 3, 'speed': 3, 'smarts': 2, 'social': 2, 'power': 5},
        9:{'strength': 4, 'speed': 3, 'smarts': 2, 'social': 2, 'power': 6},
        10:{'strength': 4, 'speed': 4, 'smarts': 2, 'social': 2, 'power': 6},
        11:{'strength': 4, 'speed': 4, 'smarts': 2, 'social': 3, 'power': 7},
        12:{'strength': 4, 'speed': 4, 'smarts': 3, 'social': 3, 'power': 7},
        13:{'strength': 5, 'speed': 4, 'smarts': 3, 'social': 3, 'power': 8},
        14:{'strength': 5, 'speed': 5, 'smarts': 3, 'social': 3, 'power': 8},
        15:{'strength': 5, 'speed': 5, 'smarts': 3, 'social': 4, 'power': 9},
        16:{'strength': 6, 'speed': 5, 'smarts': 3, 'social': 4, 'power': 9},
        17:{'strength': 6, 'speed': 6, 'smarts': 3, 'social': 4, 'power': 10},
        18:{'strength': 7, 'speed': 6, 'smarts': 3, 'social': 4, 'power': 10},
        19:{'strength': 7, 'speed': 7, 'smarts': 3, 'social': 4, 'power': 11},
        20:{'strength': 8, 'speed': 7, 'smarts': 3, 'social': 4, 'power': 11},
        },
    'Yellow':{
        1:{'strength': 0, 'speed': 2, 'smarts': 1, 'social': 0, 'power': 2},
        2:{'strength': 0, 'speed': 2, 'smarts': 2, 'social': 0, 'power': 2},
        3:{'strength': 1, 'speed': 2, 'smarts': 2, 'social': 0, 'power': 3},
        4:{'strength': 1, 'speed': 2, 'smarts': 2, 'social': 1, 'power': 3},
        5:{'strength': 1, 'speed': 3, 'smarts': 2, 'social': 1, 'power': 4},
        6:{'strength': 1, 'speed': 3, 'smarts': 3, 'social': 1, 'power': 4},
        7:{'strength': 2, 'speed': 3, 'smarts': 3, 'social': 1, 'power': 5},
        8:{'strength': 2, 'speed': 3, 'smarts': 3, 'social': 2, 'power': 5},
        9:{'strength': 2, 'speed': 4, 'smarts': 3, 'social': 2, 'power': 6},
        10:{'strength': 2, 'speed': 4, 'smarts': 4, 'social': 2, 'power': 6},
        11:{'strength': 3, 'speed': 4, 'smarts': 4, 'social': 2, 'power': 7},
        12:{'strength': 3, 'speed': 4, 'smarts': 4, 'social': 3, 'power': 7},
        13:{'strength': 3, 'speed': 5, 'smarts': 4, 'social': 3, 'power': 8},
        14:{'strength': 3, 'speed': 5, 'smarts': 5, 'social': 3, 'power': 8},
        15:{'strength': 4, 'speed': 5, 'smarts': 5, 'social': 3, 'power': 9},
        16:{'strength': 4, 'speed': 6, 'smarts': 5, 'social': 3, 'power': 9},
        17:{'strength': 4, 'speed': 6, 'smarts': 6, 'social': 3, 'power': 10},
        18:{'strength': 4, 'speed': 7, 'smarts': 6, 'social': 3, 'power': 10},
        19:{'strength': 4, 'speed': 7, 'smarts': 7, 'social': 3, 'power': 11},
        20:{'strength': 4, 'speed': 8, 'smarts': 7, 'social': 3, 'power': 11},
        },
    'Black':{
        1:{'strength': 1, 'speed': 0, 'smarts': 0, 'social': 2, 'power': 2},
        2:{'strength': 2, 'speed': 0, 'smarts': 0, 'social': 2, 'power': 2},
        3:{'strength': 2, 'speed': 0, 'smarts': 1, 'social': 2, 'power': 2},
        4:{'strength': 2, 'speed': 1, 'smarts': 1, 'social': 2, 'power': 2},
        5:{'strength': 2, 'speed': 1, 'smarts': 1, 'social': 3, 'power': 4},
        6:{'strength': 3, 'speed': 1, 'smarts': 1, 'social': 3, 'power': 4},
        7:{'strength': 3, 'speed': 1, 'smarts': 2, 'social': 3, 'power': 4},
        8:{'strength': 3, 'speed': 2, 'smarts': 2, 'social': 3, 'power': 4},
        9:{'strength': 3, 'speed': 2, 'smarts': 2, 'social': 4, 'power': 6},
        10:{'strength': 4, 'speed': 2, 'smarts': 2, 'social': 4, 'power': 6},
        11:{'strength': 4, 'speed': 2, 'smarts': 3, 'social': 4, 'power': 6},
        12:{'strength': 4, 'speed': 3, 'smarts': 3, 'social': 4, 'power': 6},
        13:{'strength': 4, 'speed': 3, 'smarts': 3, 'social': 5, 'power': 8},
        14:{'strength': 5, 'speed': 3, 'smarts': 3, 'social': 5, 'power': 8},
        15:{'strength': 5, 'speed': 3, 'smarts': 4, 'social': 5, 'power': 8},
        16:{'strength': 5, 'speed': 3, 'smarts': 4, 'social': 6, 'power': 8},
        17:{'strength': 6, 'speed': 3, 'smarts': 4, 'social': 6, 'power': 10},
        18:{'strength': 6, 'speed': 3, 'smarts': 4, 'social': 7, 'power': 10},
        19:{'strength': 7, 'speed': 3, 'smarts': 4, 'social': 7, 'power': 10},
        20:{'strength': 7, 'speed': 3, 'smarts': 4, 'social': 8, 'power': 10},
        }
}
## ranger powers are also hard-coded
Power = {
        'Pink':{'Ability':'Volley', 'Number':'2', 'Desc':'At 1st level, your Pink Ranger skills with a ranged Power Weapon are such that you can use your Morphin Grid power to launch a volley of attacks instead of a single shot. By spending 1 Personal Power, you may make a special Volley attack action as long as you do not move. This Volley attack action allows you to make a number of ranged attacks against valid targets equal to the Volley Shots number listed on the table above. Range, cover, and other modifiers apply to these targets individually.'},
        'Red':{'Ability':'Power Strike','Number':'1d2', 'Desc':'At 1st level, a Red Ranger’s attacks can be direct conduits to their raw Morphin Grid energy. You can, when making any form of melee attack while Morphed, spend 1 Personal Power to add a number of bonus Damage to the attack if successful.'},
        'Blue':{'Ability': 'Eurkea!',' Number':'1','Desc':'From the beginning of their career as a Blue Ranger at 1st level, you are constantly inspired on ways to do things that exemplify your wit and intelligence. You receive a number of Idea Points per day as listed on the table above. At any point where you are about to make a skill check with a Smarts skill, you may spend an Idea Point to gain Edge on that roll.'},
        'Green':{'Ability': 'Solo Strike', 'Number':'+1', 'Desc':'Starting at 1st level, the Green Ranger is skilled at picking a single target and going at it one on one. This Role Perk allows you to make a special kind of melee attack. By making only a single attack against an adjacent target which is also not adjacent to any of your allies, you may apply the dice shift listed on the table above. Hit or miss, you may not make any other attacks in the round in which you attempt a Solo Strike.'},
        'Yelow':{'Ability': 'Triple Strike Attacks', 'Number':'1d2', 'Desc':'Yellow Rangers at 1st level have already begun to show their talent at unleashing flurries of blows. You can, whenever you make an Finesse attack action, spend a Personal Power to make an attack with EACH of your hands at no penalty, and then make a third, Follow-Up martial arts attack at a target of one of the previous strikes. This follow-up attack – often a kick, elbow, or headbutt – has a variable skill die based on your Yellow Ranger level, shown on the table above.'},
        'Black':{'Ability': 'Quips and Speeches', 'Number':'2', 'Desc':'Beginning at 1st level, your natural mirth and positivity can be used to boost your teammates and other allies with just a few words. Whether in the heat of battle or at the peak of a difficult obstacle, your clever words can make the difference between failure and success. As a Free Action, you can apply a 1 shift to the roll of any ally within 60 feet of you that can understand what you are saying. This costs one of your Quips & Speeches per long rest, as noted on the table above. The value of this die rolled increases to the listed amount at 5th, 10th, and 15th levels.'}
        }
    