# Form implementation generated from reading ui file 'PRTTRPG_charactercreaditor.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow1):
        MainWindow1.setObjectName("MainWindow1")
        MainWindow1.resize(800, 724)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 210, 151, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_9 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(420, 500, 141, 31))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.CharDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CharDisplay.setGeometry(QtCore.QRect(350, 630, 101, 51))
        self.CharDisplay.setObjectName("CharDisplay")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(60, 330, 151, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_10 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(600, 500, 141, 31))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.CharLevel = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CharLevel.setGeometry(QtCore.QRect(250, 270, 61, 22))
        self.CharLevel.setObjectName("CharLevel")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharLevel.addItem("")
        self.CharOrDesc = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharOrDesc.setGeometry(QtCore.QRect(420, 290, 361, 91))
        self.CharOrDesc.setObjectName("CharOrDesc")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(60, 270, 151, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(260, 540, 104, 41))
        self.textEdit_2.setObjectName("textEdit_2")
        self.CharOrigin = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CharOrigin.setGeometry(QtCore.QRect(250, 330, 111, 22))
        self.CharOrigin.setObjectName("CharOrigin")
        self.CharOrigin.addItem("")
        self.CharOrigin.addItem("")
        self.CharOrigin.addItem("")
        self.CharOrigin.addItem("")
        self.CharOrigin.addItem("")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(610, 540, 104, 41))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(60, 390, 141, 31))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_8 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(240, 500, 141, 31))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_6 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(340, 450, 141, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.CharName = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.CharName.setGeometry(QtCore.QRect(250, 210, 131, 31))
        self.CharName.setObjectName("CharName")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(250, 0, 321, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_7 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(60, 500, 141, 31))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(440, 540, 104, 41))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 540, 104, 41))
        self.textEdit.setObjectName("textEdit")
        self.CharRColor = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CharRColor.setGeometry(QtCore.QRect(250, 400, 141, 22))
        self.CharRColor.setObjectName("CharRColor")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        self.CharRColor.addItem("")
        MainWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow1)
        self.statusbar.setObjectName("statusbar")
        MainWindow1.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow1)

    def retranslateUi(self, MainWindow1):
        _translate = QtCore.QCoreApplication.translate
        MainWindow1.setWindowTitle(_translate("MainWindow1", "MainWindow1"))
        self.textBrowser_2.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Character Name:</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Smarts</span></p></body></html>"))
        self.CharDisplay.setText(_translate("MainWindow1", "Create Character"))
        self.textBrowser_4.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Character Origin:</span></p></body></html>"))
        self.textBrowser_10.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Social</span></p></body></html>"))
        self.CharLevel.setItemText(0, _translate("MainWindow1", "1"))
        self.CharLevel.setItemText(1, _translate("MainWindow1", "2"))
        self.CharLevel.setItemText(2, _translate("MainWindow1", "3"))
        self.CharLevel.setItemText(3, _translate("MainWindow1", "4"))
        self.CharLevel.setItemText(4, _translate("MainWindow1", "5"))
        self.CharLevel.setItemText(5, _translate("MainWindow1", "6"))
        self.CharLevel.setItemText(6, _translate("MainWindow1", "7"))
        self.CharLevel.setItemText(7, _translate("MainWindow1", "8"))
        self.CharLevel.setItemText(8, _translate("MainWindow1", "9"))
        self.CharLevel.setItemText(9, _translate("MainWindow1", "10"))
        self.CharLevel.setItemText(10, _translate("MainWindow1", "11"))
        self.CharLevel.setItemText(11, _translate("MainWindow1", "12"))
        self.CharLevel.setItemText(12, _translate("MainWindow1", "13"))
        self.CharLevel.setItemText(13, _translate("MainWindow1", "14"))
        self.CharLevel.setItemText(14, _translate("MainWindow1", "15"))
        self.CharLevel.setItemText(15, _translate("MainWindow1", "16"))
        self.CharLevel.setItemText(16, _translate("MainWindow1", "17"))
        self.CharLevel.setItemText(17, _translate("MainWindow1", "18"))
        self.CharLevel.setItemText(18, _translate("MainWindow1", "19"))
        self.CharLevel.setItemText(19, _translate("MainWindow1", "20"))
        self.CharOrDesc.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-style:italic;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Origin Benefit will appear here</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Character Level:</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Place speed score here</span></p></body></html>"))
        self.CharOrigin.setItemText(0, _translate("MainWindow1", "Choose an Origin"))
        self.CharOrigin.setItemText(1, _translate("MainWindow1", "Athletic"))
        self.CharOrigin.setItemText(2, _translate("MainWindow1", "Brainy"))
        self.CharOrigin.setItemText(3, _translate("MainWindow1", "Comedic"))
        self.CharOrigin.setItemText(4, _translate("MainWindow1", "Curious"))
        self.textEdit_4.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Place social score here</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Ranger Color:</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Speed</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Essence Scores</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">Power Rangers </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">Table Top Roleplaying Game</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Strength</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Place smarts score here</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic;\">Place strength score here</span></p></body></html>"))
        self.CharRColor.setItemText(0, _translate("MainWindow1", "Choose a Ranger Color"))
        self.CharRColor.setItemText(1, _translate("MainWindow1", "Red"))
        self.CharRColor.setItemText(2, _translate("MainWindow1", "Blue"))
        self.CharRColor.setItemText(3, _translate("MainWindow1", "Black"))
        self.CharRColor.setItemText(4, _translate("MainWindow1", "Pink"))
        self.CharRColor.setItemText(5, _translate("MainWindow1", "Yellow"))
        self.CharRColor.setItemText(6, _translate("MainWindow1", "Green"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow1 = QtWidgets.QMainWindow1()
    ui = Ui_MainWindow1()
    ui.setupUi(MainWindow1)
    MainWindow1.show()
    sys.exit(app.exec())
