# Form implementation generated from reading ui file 'PRTTRPG_charactersheet.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(800, 736)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.CharSmrtDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharSmrtDisplay.setGeometry(QtCore.QRect(440, 470, 141, 31))
        self.CharSmrtDisplay.setObjectName("CharSmrtDisplay")
        self.CharMEvaDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharMEvaDisplay.setGeometry(QtCore.QRect(260, 580, 141, 31))
        self.CharMEvaDisplay.setObjectName("CharMEvaDisplay")
        self.CharMClevDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharMClevDisplay.setGeometry(QtCore.QRect(620, 580, 141, 31))
        self.CharMClevDisplay.setObjectName("CharMClevDisplay")
        self.CharNDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharNDisplay.setGeometry(QtCore.QRect(50, 170, 161, 51))
        self.CharNDisplay.setObjectName("CharNDisplay")
        self.CharEvaDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharEvaDisplay.setGeometry(QtCore.QRect(260, 530, 141, 31))
        self.CharEvaDisplay.setObjectName("CharEvaDisplay")
        self.CharLDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharLDisplay.setGeometry(QtCore.QRect(620, 170, 161, 51))
        self.CharLDisplay.setObjectName("CharLDisplay")
        self.CharClevDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharClevDisplay.setGeometry(QtCore.QRect(620, 530, 141, 31))
        self.CharClevDisplay.setObjectName("CharClevDisplay")
        self.CharMSDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharMSDisplay.setGeometry(QtCore.QRect(440, 250, 161, 51))
        self.CharMSDisplay.setObjectName("CharMSDisplay")
        self.CharHDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharHDisplay.setGeometry(QtCore.QRect(440, 170, 161, 51))
        self.CharHDisplay.setObjectName("CharHDisplay")
        self.CharRCDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharRCDisplay.setGeometry(QtCore.QRect(230, 170, 161, 51))
        self.CharRCDisplay.setObjectName("CharRCDisplay")
        self.CharToughDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharToughDisplay.setGeometry(QtCore.QRect(80, 530, 141, 31))
        self.CharToughDisplay.setObjectName("CharToughDisplay")
        self.CharRADisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharRADisplay.setGeometry(QtCore.QRect(230, 230, 161, 131))
        self.CharRADisplay.setObjectName("CharRADisplay")
        self.CharPDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharPDisplay.setGeometry(QtCore.QRect(620, 250, 161, 51))
        self.CharPDisplay.setObjectName("CharPDisplay")
        self.CharStrDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharStrDisplay.setGeometry(QtCore.QRect(80, 470, 141, 31))
        self.CharStrDisplay.setObjectName("CharStrDisplay")
        self.EditChar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.EditChar.setGeometry(QtCore.QRect(380, 640, 101, 51))
        self.EditChar.setObjectName("EditChar")
        self.CharMToughDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharMToughDisplay.setGeometry(QtCore.QRect(80, 580, 141, 31))
        self.CharMToughDisplay.setObjectName("CharMToughDisplay")
        self.CharSpdDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharSpdDisplay.setGeometry(QtCore.QRect(260, 470, 141, 31))
        self.CharSpdDisplay.setObjectName("CharSpdDisplay")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(260, 0, 321, 131))
        self.textBrowser.setObjectName("textBrowser")
        self.CharSocDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharSocDisplay.setGeometry(QtCore.QRect(620, 470, 141, 31))
        self.CharSocDisplay.setObjectName("CharSocDisplay")
        self.CharWillDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharWillDisplay.setGeometry(QtCore.QRect(440, 530, 141, 31))
        self.CharWillDisplay.setObjectName("CharWillDisplay")
        self.CharODisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharODisplay.setGeometry(QtCore.QRect(50, 250, 161, 51))
        self.CharODisplay.setObjectName("CharODisplay")
        self.CharMWillDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharMWillDisplay.setGeometry(QtCore.QRect(440, 580, 141, 31))
        self.CharMWillDisplay.setObjectName("CharMWillDisplay")
        self.CharODescDisplay = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.CharODescDisplay.setGeometry(QtCore.QRect(50, 320, 161, 101))
        self.CharODescDisplay.setObjectName("CharODescDisplay")
        self.textBrowser_15 = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(360, 420, 141, 31))
        self.textBrowser_15.setObjectName("textBrowser_15")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "MainWindow2"))
        self.CharSmrtDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharMEvaDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharMClevDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharEvaDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharClevDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharToughDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharStrDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.EditChar.setText(_translate("MainWindow2", "Edit Character"))
        self.CharMToughDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharSpdDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">Power Rangers </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt; font-weight:600;\">Table Top Roleplaying Game</span></p></body></html>"))
        self.CharSocDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharWillDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CharMWillDisplay.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_15.setHtml(_translate("MainWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Essence Scores</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow2()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec())
